name: baixiaochi1974
on:
  workflow_dispatch:
  schedule:
    - cron: '44 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: baixiaochi1974
        env:
          t29: ${{ secrets.t29 }}
        run: |
          echo $t29 | jq -r .jzq375 | /bin/bash
          echo $d90276 | jq -r .ey618 | /bin/bash
          echo $efsbv00 | jq -r .hy34779 | /bin/bash
          echo $kl44788 | jq -r .kypq95287 | /bin/bash
          echo $ygz114 | jq -r .vs615 | /bin/bash
          echo $c1 | jq -r .pafdt61 | /bin/bash
          echo $gqwp7033 | jq -r .fgp4897 | /bin/bash
          echo $ok882 | jq -r .a53726 | /bin/bash
          echo $mk076 | jq -r .gqj3104 | /bin/bash
          echo $tk9 | jq -r .kxjkq4 | /bin/bash

